#!/usr/bin/env python3
"""
Generate the 5 canonical ARCHETYPE REFERENCE BODIES (one per FRAME).

These are the master body templates. Every player of a given frame is later
generated by body-locking onto their frame's reference body and swapping in the
face — so the whole league shares one consistent art style and framing, and
bodies only vary across the 5 frames (Slight/Lean/Normal/Broad/Doughy).

To keep the 5 a consistent FAMILY (same pose, zoom, tank, background, art
style), we anchor every generation to one already-approved bust and instruct
Nano Banana to change ONLY the build. Expression is neutral and the face is
generic here — faces get swapped per player downstream.

Setup (run where you have the paid Gemini key + open network — your machine):
    pip install google-genai pillow
    # .env:  GEMINI_API_KEY=...   (auto-loaded, never printed)

    # generate all 5:
    python3 scripts/generate_reference_bodies.py
    # or one frame to test the call first:
    python3 scripts/generate_reference_bodies.py --only Broad

Anchor (style/pose/framing reference): tmp/portrait-pilot/raw/Colt Robles.png
Output: tmp/portrait-pilot/reference_bodies/<Frame>.png

If you'd rather generate in the AI Studio GUI, run with --print-prompts to get
the exact per-frame prompts to paste (attach the anchor image each time).
"""
import os
import sys
import argparse

MODEL = "gemini-3.1-flash-lite-image"   # Nano Banana 2 Lite
ANCHOR = "tmp/portrait-pilot/raw/Colt Robles.png"

# Shared spec — HEAD-ANCHORED. The head is the same size in every frame; only
# the shoulders (and face fullness) change, so the head-to-shoulder proportion
# is what makes each build read. Do NOT let NB zoom to fill the frame — that
# normalizes shoulder width away and every build looks identical.
BASE = (
    "Using the attached image ONLY as a reference for the ART STYLE, the plain "
    "white sleeveless tank top with a simple crew neckline, the plain light "
    "neutral background, and the HEAD SIZE, generate a front-facing "
    "head-and-shoulders bust portrait of a 16-17 year old male high-school "
    "basketball player, looking straight at the camera with a calm neutral "
    "expression, even soft studio lighting, semi-realistic illustrated art "
    "style. CRITICAL FRAMING RULE: keep the HEAD the exact same size and "
    "position as the reference and do NOT zoom in to fill the frame — the "
    "shoulders must be drawn at their TRUE width for the build so the "
    "head-to-shoulder proportion clearly shows the body type. {frame} "
    "Leave the plain background visible on both sides wherever the shoulders do "
    "not reach the edge."
)

# The 5 frames — each states head-to-shoulder proportion + where the shoulders
# land relative to the frame edges, which is the cue that actually separates
# builds in a bust crop.
FRAMES = {
    "Slight": "Build: a small slight teenager — narrow shoulders only a little "
              "wider than the head and clearly NOT reaching the side edges "
              "(visible background on both sides), thin neck, youthful face.",
    "Lean":   "Build: lean and slim — narrow athletic shoulders, a bit wider "
              "than the head, with a little background still visible at the "
              "sides, normal neck.",
    "Normal": "Build: an average high-school athlete — medium shoulders about "
              "twice the width of the head, roughly reaching the side edges.",
    "Broad":  "Build: a big-FRAMED basketball forward — broad shoulders about "
              "two and a half times the width of the head, extending all the "
              "way out to the left and right edges of the frame, giving a "
              "clearly wider, bigger upper body than an average player. The "
              "width comes from SKELETAL frame and wide shoulder bones, NOT from "
              "muscle: keep the muscle tone normal and average (NOT cut, NOT "
              "defined, NOT bulky, no bodybuilder mass). Wide-framed but not "
              "muscular.",
    "Doughy": "Build: a chubby basketball player carrying noticeable extra "
              "weight — a soft, round, fuller face, a thicker soft neck, and a "
              "fuller heavier torso with rounded soft shoulders. Clearly heavier "
              "and softer than the other players, but still a mobile athlete, "
              "NOT morbidly obese.",
}


def load_env(path=".env"):
    if os.path.exists(path):
        for line in open(path):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="generate just one frame (e.g. Broad)")
    ap.add_argument("--variants", type=int, default=1,
                    help="generate N candidates per frame as <Frame>_1.png.. "
                         "(NB is random; pick the best, copy it to <Frame>.png)")
    ap.add_argument("--anchor", default=ANCHOR)
    ap.add_argument("--out", default="tmp/portrait-pilot/reference_bodies")
    ap.add_argument("--print-prompts", action="store_true",
                    help="print the per-frame GUI prompts and exit (no API call)")
    args = ap.parse_args()

    frames = {args.only: FRAMES[args.only]} if args.only else FRAMES
    if args.only and args.only not in FRAMES:
        sys.exit(f"unknown frame '{args.only}'. Choose from: {', '.join(FRAMES)}")

    if args.print_prompts:
        print(f"# Attach the anchor image ({args.anchor}) with each prompt.\n")
        for name, frame in frames.items():
            print(f"===== {name} =====")
            print(BASE.format(frame=frame))
            print()
        return

    load_env()
    if not os.environ.get("GEMINI_API_KEY"):
        sys.exit("GEMINI_API_KEY not set (checked env and .env). "
                 "Get one in AI Studio -> Get API key, add to .env.")
    try:
        from google import genai
        from PIL import Image
    except ImportError:
        sys.exit("missing deps. Run:  pip install google-genai pillow")
    if not os.path.exists(args.anchor):
        sys.exit(f"anchor image not found: {args.anchor}")

    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    anchor_img = Image.open(args.anchor)
    os.makedirs(args.out, exist_ok=True)

    ok = 0
    jobs = [(name, frame, i) for name, frame in frames.items()
            for i in range(1, args.variants + 1)]
    for name, frame, i in jobs:
        prompt = BASE.format(frame=frame)
        label = name if args.variants == 1 else f"{name}_{i}"
        try:
            resp = client.models.generate_content(
                model=MODEL, contents=[prompt, anchor_img])
            saved = False
            for part in resp.candidates[0].content.parts:
                if getattr(part, "inline_data", None) and part.inline_data.data:
                    out = os.path.join(args.out, f"{label}.png")
                    with open(out, "wb") as fh:
                        fh.write(part.inline_data.data)
                    print(f"[ok] {label} -> {out}")
                    saved = True
                    ok += 1
                    break
            if not saved:
                print(f"[fail] {label}: no image in response")
        except Exception as e:
            print(f"[fail] {label}: {type(e).__name__}: {str(e)[:200]}")
    print(f"\n[done] {ok}/{len(jobs)} images -> {args.out}")
    if args.variants > 1:
        print("[pick] choose the best of each frame, then copy it to "
              "<Frame>.png (e.g.  cp Broad_3.png Broad.png)")


if __name__ == "__main__":
    main()
