#!/usr/bin/env python3
"""
Generate the 5 canonical ARCHETYPE REFERENCE BODIES (one per FRAME).

These are the master body templates. Every player of a given frame is later
generated by body-locking onto their frame's reference body and swapping in the
face — so the whole league shares one consistent art style and framing, and
bodies only vary across the 5 frames (Slight/Lean/Normal/Broad/Doughy).

To keep the 5 a consistent FAMILY (same pose, zoom, tank, background, art
style), we anchor every generation to one already-approved bust and instruct
Nano Banana to change ONLY the build. Expression is neutral and the face is
generic here — faces get swapped per player downstream.

Setup (run where you have the paid Gemini key + open network — your machine):
    pip install google-genai pillow
    # .env:  GEMINI_API_KEY=...   (auto-loaded, never printed)

    # generate all 5:
    python3 scripts/generate_reference_bodies.py
    # or one frame to test the call first:
    python3 scripts/generate_reference_bodies.py --only Broad

Anchor (style/pose/framing reference): tmp/portrait-pilot/raw/Colt Robles.png
Output: tmp/portrait-pilot/reference_bodies/<Frame>.png

If you'd rather generate in the AI Studio GUI, run with --print-prompts to get
the exact per-frame prompts to paste (attach the anchor image each time).
"""
import os
import sys
import argparse

MODEL = "gemini-3.1-flash-lite-image"   # Nano Banana 2 Lite
ANCHOR = "tmp/portrait-pilot/raw/Colt Robles.png"

# Shared spec — identical across all 5 so the family stays consistent.
BASE = (
    "Using the attached image ONLY as a reference for the ART STYLE, pose, "
    "camera framing/zoom, plain white sleeveless tank top with a simple crew "
    "neckline, and plain light neutral background, generate a front-facing "
    "head-and-shoulders bust portrait of a 16-17 year old male high-school "
    "basketball player, looking straight at the camera with a calm neutral "
    "expression, even soft studio lighting, semi-realistic illustrated art "
    "style. Keep the pose, framing, zoom, white tank, neckline, and background "
    "IDENTICAL to the reference. Change ONLY the body build to: {frame}. "
    "Full shoulders visible, upper chest at the bottom edge."
)

# The 5 frames — the ONLY thing that varies between the reference bodies.
FRAMES = {
    "Slight": "a small slight teenage frame — narrow shoulders, thin neck, "
              "lean youthful build, head slightly large for the body",
    "Lean":   "a lean slim wiry frame with narrow athletic shoulders and a "
              "normal neck",
    "Normal": "an average athletic frame with medium shoulders, a typical "
              "high-school athlete build",
    "Broad":  "a big powerful frame with very broad wide shoulders that fill "
              "the width of the frame and a thick neck",
    "Doughy": "a soft heavyset frame — rounded sloping shoulders, a full "
              "torso, a thick soft neck, and a fuller rounder face",
}


def load_env(path=".env"):
    if os.path.exists(path):
        for line in open(path):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="generate just one frame (e.g. Broad)")
    ap.add_argument("--anchor", default=ANCHOR)
    ap.add_argument("--out", default="tmp/portrait-pilot/reference_bodies")
    ap.add_argument("--print-prompts", action="store_true",
                    help="print the per-frame GUI prompts and exit (no API call)")
    args = ap.parse_args()

    frames = {args.only: FRAMES[args.only]} if args.only else FRAMES
    if args.only and args.only not in FRAMES:
        sys.exit(f"unknown frame '{args.only}'. Choose from: {', '.join(FRAMES)}")

    if args.print_prompts:
        print(f"# Attach the anchor image ({args.anchor}) with each prompt.\n")
        for name, frame in frames.items():
            print(f"===== {name} =====")
            print(BASE.format(frame=frame))
            print()
        return

    load_env()
    if not os.environ.get("GEMINI_API_KEY"):
        sys.exit("GEMINI_API_KEY not set (checked env and .env). "
                 "Get one in AI Studio -> Get API key, add to .env.")
    try:
        from google import genai
        from PIL import Image
    except ImportError:
        sys.exit("missing deps. Run:  pip install google-genai pillow")
    if not os.path.exists(args.anchor):
        sys.exit(f"anchor image not found: {args.anchor}")

    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    anchor_img = Image.open(args.anchor)
    os.makedirs(args.out, exist_ok=True)

    ok = 0
    for name, frame in frames.items():
        prompt = BASE.format(frame=frame)
        try:
            resp = client.models.generate_content(
                model=MODEL, contents=[prompt, anchor_img])
            saved = False
            for part in resp.candidates[0].content.parts:
                if getattr(part, "inline_data", None) and part.inline_data.data:
                    out = os.path.join(args.out, f"{name}.png")
                    with open(out, "wb") as fh:
                        fh.write(part.inline_data.data)
                    print(f"[ok] {name} -> {out}")
                    saved = True
                    ok += 1
                    break
            if not saved:
                print(f"[fail] {name}: no image in response")
        except Exception as e:
            print(f"[fail] {name}: {type(e).__name__}: {str(e)[:200]}")
    print(f"\n[done] {ok}/{len(frames)} reference bodies -> {args.out}")


if __name__ == "__main__":
    main()
