#!/usr/bin/env python3
"""
Generate the 5 canonical ARCHETYPE REFERENCE BODIES (one per FRAME).

These are the master body templates. Every player of a given frame is later
generated by body-locking onto their frame's reference body and swapping in the
face — so the whole league shares one consistent art style and framing, and
bodies only vary across the 5 frames (Slight/Lean/Normal/Broad/Doughy).

To keep the 5 a consistent FAMILY (same pose, zoom, tank, background, art
style), we anchor every generation to one already-approved bust and instruct
Nano Banana to change ONLY the build. Expression is neutral and the face is
generic here — faces get swapped per player downstream.

Setup (run where you have the paid Gemini key + open network — your machine):
    pip install google-genai pillow
    # .env:  GEMINI_API_KEY=...   (auto-loaded, never printed)

    # generate all 5:
    python3 scripts/generate_reference_bodies.py
    # or one frame to test the call first:
    python3 scripts/generate_reference_bodies.py --only Broad

Anchor (style/pose/framing reference): tmp/portrait-pilot/raw/Colt Robles.png
Output: tmp/portrait-pilot/reference_bodies/<Frame>.png

If you'd rather generate in the AI Studio GUI, run with --print-prompts to get
the exact per-frame prompts to paste (attach the anchor image each time).
"""
import os
import sys
import argparse

MODEL = "gemini-3.1-flash-lite-image"   # Nano Banana 2 Lite
ANCHOR = "tmp/portrait-pilot/raw/Colt Robles.png"

# Per-frame anchor override. NB would not widen the frame off Colt's narrow
# body no matter the wording, so Broad takes TWO references: a genuinely
# broad-shouldered Conf1 player (Cedric Buckles) for the BODY WIDTH, and the
# shared Colt anchor for the young face / hair / illustrated style / background
# (copying Buckles alone dragged in his adult face, dreads, and photo-real look).
# Values may be a single path or a list (image 1, image 2, ...).
_BUCKLES = "FrontEnd/static/images/players/0df15c02-a4d1-437b-b102-45f42b25e50b.png"
FRAME_ANCHORS = {
    "Broad": [_BUCKLES, ANCHOR],
}

# Full-prompt override for frames whose anchor already HAS the target build.
FRAME_FULL_PROMPT = {
    "Broad":
        "Two reference images are attached. IMAGE 1 is for BODY BUILD ONLY: "
        "copy its big, imposing frame — broad shoulders that bleed off the left "
        "and right edges of the frame, and an overall large-and-physical read. "
        "He should look like a BIG kid: a slightly larger head and heavier "
        "overall proportions, cropped tight so the body fills and slightly "
        "overflows the frame. IMAGE 2 is for STYLE ONLY: match its youthful "
        "16-17 year old face and age, short simple hair, semi-realistic "
        "illustrated art style, plain light neutral background, and white "
        "sleeveless tank. Generate a front-facing head-and-shoulders bust of a "
        "16-17 year old high-school basketball player who reads as a big, "
        "broad-framed kid (from image 1) drawn in the young illustrated look of "
        "image 2, calm neutral expression, plain average muscle tone (not cut, "
        "not bulky). Do NOT copy image 1's face, hair, skin tone, or "
        "background — only its big build and proportions.",
}

# Shared spec — HEAD-ANCHORED. The head is the same size in every frame; only
# the shoulders (and face fullness) change, so the head-to-shoulder proportion
# is what makes each build read. Do NOT let NB zoom to fill the frame — that
# normalizes shoulder width away and every build looks identical.
BASE = (
    "Using the attached image ONLY as a reference for the ART STYLE, the plain "
    "white sleeveless tank top with a simple crew neckline, the plain light "
    "neutral background, and the HEAD SIZE, generate a front-facing "
    "head-and-shoulders bust portrait of a 16-17 year old male high-school "
    "basketball player, looking straight at the camera with a calm neutral "
    "expression, even soft studio lighting, semi-realistic illustrated art "
    "style. CRITICAL FRAMING RULE: keep the HEAD the exact same size and "
    "position as the reference and do NOT zoom in to fill the frame — the "
    "shoulders must be drawn at their TRUE width for the build so the "
    "head-to-shoulder proportion clearly shows the body type. {frame} "
    "Leave the plain background visible on both sides wherever the shoulders do "
    "not reach the edge."
)

# The 5 frames — each states head-to-shoulder proportion + where the shoulders
# land relative to the frame edges, which is the cue that actually separates
# builds in a bust crop.
FRAMES = {
    "Slight": "Build: a small slight teenager — narrow shoulders only a little "
              "wider than the head and clearly NOT reaching the side edges "
              "(visible background on both sides), thin neck, youthful face.",
    "Lean":   "Build: lean and slim — narrow athletic shoulders, a bit wider "
              "than the head, with a little background still visible at the "
              "sides, normal neck.",
    "Normal": "Build: an average high-school athlete — medium shoulders about "
              "twice the width of the head, roughly reaching the side edges.",
    "Broad":  "Build: a big-FRAMED basketball forward. His shoulders are so "
              "wide they are CROPPED by the left and right edges of the frame "
              "and bleed off both sides — clearly much wider than the head and "
              "much wider than an average player. The width comes purely from a "
              "large SKELETAL frame and wide shoulder bones, NOT from muscle: "
              "keep the muscle tone plain and average (NOT cut, NOT defined, NOT "
              "bulky, no visible muscle definition). A wide-framed, big-boned "
              "teenager, not a muscular one.",
    "Doughy": "Build: a chubby basketball player carrying noticeable extra "
              "weight — a soft, round, fuller face, a thicker soft neck, and a "
              "fuller heavier torso with rounded soft shoulders. Clearly heavier "
              "and softer than the other players, but still a mobile athlete, "
              "NOT morbidly obese.",
}


def load_env(path=".env"):
    if os.path.exists(path):
        for line in open(path):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="generate just one frame (e.g. Broad)")
    ap.add_argument("--variants", type=int, default=1,
                    help="generate N candidates per frame as <Frame>_1.png.. "
                         "(NB is random; pick the best, copy it to <Frame>.png)")
    ap.add_argument("--anchor", default=ANCHOR)
    ap.add_argument("--out", default="tmp/portrait-pilot/reference_bodies")
    ap.add_argument("--print-prompts", action="store_true",
                    help="print the per-frame GUI prompts and exit (no API call)")
    args = ap.parse_args()

    frames = {args.only: FRAMES[args.only]} if args.only else FRAMES
    if args.only and args.only not in FRAMES:
        sys.exit(f"unknown frame '{args.only}'. Choose from: {', '.join(FRAMES)}")

    if args.print_prompts:
        for name, frame in frames.items():
            anchor = FRAME_ANCHORS.get(name, args.anchor)
            print(f"===== {name}  (attach: {anchor}) =====")
            print(FRAME_FULL_PROMPT.get(name) or BASE.format(frame=frame))
            print()
        return

    load_env()
    if not os.environ.get("GEMINI_API_KEY"):
        sys.exit("GEMINI_API_KEY not set (checked env and .env). "
                 "Get one in AI Studio -> Get API key, add to .env.")
    try:
        from google import genai
        from PIL import Image
    except ImportError:
        sys.exit("missing deps. Run:  pip install google-genai pillow")
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    os.makedirs(args.out, exist_ok=True)
    _anchor_cache = {}

    def anchor_for(name):
        paths = FRAME_ANCHORS.get(name, args.anchor)
        if isinstance(paths, str):
            paths = [paths]
        imgs = []
        for path in paths:
            if path not in _anchor_cache:
                if not os.path.exists(path):
                    sys.exit(f"anchor image not found: {path}")
                _anchor_cache[path] = Image.open(path)
            imgs.append(_anchor_cache[path])
        return imgs

    ok = 0
    jobs = [(name, frame, i) for name, frame in frames.items()
            for i in range(1, args.variants + 1)]
    for name, frame, i in jobs:
        prompt = FRAME_FULL_PROMPT.get(name) or BASE.format(frame=frame)
        label = name if args.variants == 1 else f"{name}_{i}"
        try:
            resp = client.models.generate_content(
                model=MODEL, contents=[prompt, *anchor_for(name)])
            saved = False
            for part in resp.candidates[0].content.parts:
                if getattr(part, "inline_data", None) and part.inline_data.data:
                    out = os.path.join(args.out, f"{label}.png")
                    with open(out, "wb") as fh:
                        fh.write(part.inline_data.data)
                    print(f"[ok] {label} -> {out}")
                    saved = True
                    ok += 1
                    break
            if not saved:
                print(f"[fail] {label}: no image in response")
        except Exception as e:
            print(f"[fail] {label}: {type(e).__name__}: {str(e)[:200]}")
    print(f"\n[done] {ok}/{len(jobs)} images -> {args.out}")
    if args.variants > 1:
        print("[pick] choose the best of each frame, then copy it to "
              "<Frame>.png (e.g.  cp Broad_3.png Broad.png)")


if __name__ == "__main__":
    main()
