#!/usr/bin/env python3
"""
Sync fallback FCP/HCT skeleton python files from MongoDB.

This script pulls documents from BOTH:
- gob.fcp_skeletons / gob.hct_skeletons
- gob-staging.fcp_skeletons / gob-staging.hct_skeletons

Then rewrites:
- BackEnd/playcall_skeletons/fcp_skeletons.py
- BackEnd/playcall_skeletons/hct_skeletons.py

with separate "gob" and "gob-staging" sections plus compatibility constants.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from pprint import pformat
from typing import Any

from pymongo import MongoClient


ROOT = Path(__file__).resolve().parents[1]
FCP_FILE = ROOT / "BackEnd" / "playcall_skeletons" / "fcp_skeletons.py"
HCT_FILE = ROOT / "BackEnd" / "playcall_skeletons" / "hct_skeletons.py"


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        k = k.strip()
        v = v.strip().strip('"').strip("'")
        if k and k not in os.environ:
            os.environ[k] = v


def _load_mongo_uri() -> str:
    _load_env_file(ROOT / ".env.local")
    _load_env_file(ROOT / ".env")
    uri = os.environ.get("MONGO_URI")
    if not uri:
        raise RuntimeError("MONGO_URI not found in environment/.env files")
    return uri


def _clean_docs(docs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    cleaned: list[dict[str, Any]] = []
    for doc in docs:
        d = dict(doc)
        d.pop("_id", None)
        cleaned.append(d)
    return cleaned


def _fetch_collection_docs(client: MongoClient, db_name: str, collection_name: str) -> list[dict[str, Any]]:
    coll = client[db_name][collection_name]
    docs = list(coll.find({}))
    return _clean_docs(docs)


def _pick_primary_doc(gob_docs: list[dict[str, Any]], staging_docs: list[dict[str, Any]]) -> dict[str, Any]:
    if gob_docs:
        return gob_docs[0]
    if staging_docs:
        return staging_docs[0]
    return {}


def _extract_steps_for_variant(doc: dict[str, Any], variant_name: str, preferred_version: str = "v1") -> list[dict[str, Any]]:
    variants = doc.get("variants") or {}
    variant = variants.get(variant_name) or {}
    versions = variant.get("versions") or []
    if not isinstance(versions, list):
        return []

    chosen = None
    for version_doc in versions:
        if not isinstance(version_doc, dict):
            continue
        if version_doc.get("version") == preferred_version and version_doc.get("steps"):
            chosen = version_doc
            break

    if chosen is None:
        for version_doc in versions:
            if isinstance(version_doc, dict) and version_doc.get("steps"):
                chosen = version_doc
                break

    if chosen is None:
        return []
    steps = chosen.get("steps") or []
    return steps if isinstance(steps, list) else []


def _module_header() -> str:
    return (
        '"""\n'
        "Auto-generated fallback skeletons from MongoDB.\n\n"
        "Source databases:\n"
        "- gob\n"
        "- gob-staging\n\n"
        "Generated by: scripts/sync_fcp_hct_fallbacks_from_db.py\n"
        '"""\n\n'
    )


def _format_py(value: Any) -> str:
    # Keep output deterministic and readable.
    return pformat(value, width=110, sort_dicts=False)


def _build_fcp_module(
    gob_docs: list[dict[str, Any]],
    staging_docs: list[dict[str, Any]],
) -> str:
    primary = _pick_primary_doc(gob_docs, staging_docs)
    base_steps = _extract_steps_for_variant(primary, "base", preferred_version="v1")

    # Keep legacy fallback behavior contract.
    fcp_1 = {
        "primary_shooter": None,
        "screener": None,
        "kickout_shooters": None,
        "steps": base_steps,
    }
    fcp_map = {
        "HCO": 1200,
        "Shot": 1800,
        "O_FOUL": 1200,
        "D_FOUL": 1200,
        "DEAD_BALL_TURNOVER": 900,
        "STEAL": 900,
    }

    return (
        _module_header()
        + "# ==================== gob skeletons ====================\n"
        + f"GOB_FCP_SKELETON_DOCS = {_format_py(gob_docs)}\n\n"
        + "# ==================== gob-staging skeletons ====================\n"
        + f"GOB_STAGING_FCP_SKELETON_DOCS = {_format_py(staging_docs)}\n\n"
        + "# ==================== compatibility fallback constants ====================\n"
        + f"FCP_1 = {_format_py(fcp_1)}\n\n"
        + f"FCP_SKELETONS_DICT = {_format_py(fcp_map)}\n"
    )


def _build_hct_module(
    gob_docs: list[dict[str, Any]],
    staging_docs: list[dict[str, Any]],
) -> str:
    primary = _pick_primary_doc(gob_docs, staging_docs)
    base_steps = _extract_steps_for_variant(primary, "base", preferred_version="v1")

    hct_1 = {
        "primary_shooter": None,
        "screener": None,
        "kickout_shooters": None,
        "steps": base_steps,
    }
    hct_map = {
        "HCO": 1200,
        "SHOT": 1800,
        "O_FOUL": 1200,
        "D_FOUL": 900,
        "DEAD_BALL_TURNOVER": 900,
        "STEAL": 900,
    }
    hct_scenes = [hct_1]

    return (
        _module_header()
        + "# ==================== gob skeletons ====================\n"
        + f"GOB_HCT_SKELETON_DOCS = {_format_py(gob_docs)}\n\n"
        + "# ==================== gob-staging skeletons ====================\n"
        + f"GOB_STAGING_HCT_SKELETON_DOCS = {_format_py(staging_docs)}\n\n"
        + "# ==================== compatibility fallback constants ====================\n"
        + f"HCT_1 = {_format_py(hct_1)}\n\n"
        + f"HCT_SKELETONS_DICT = {_format_py(hct_map)}\n\n"
        + f"HCT_SCENES = {_format_py(hct_scenes)}\n"
    )


def main() -> int:
    uri = _load_mongo_uri()
    client = MongoClient(uri, serverSelectionTimeoutMS=10000)

    fcp_gob = _fetch_collection_docs(client, "gob", "fcp_skeletons")
    fcp_staging = _fetch_collection_docs(client, "gob-staging", "fcp_skeletons")
    hct_gob = _fetch_collection_docs(client, "gob", "hct_skeletons")
    hct_staging = _fetch_collection_docs(client, "gob-staging", "hct_skeletons")

    print(f"[sync] gob.fcp_skeletons={len(fcp_gob)} gob-staging.fcp_skeletons={len(fcp_staging)}")
    print(f"[sync] gob.hct_skeletons={len(hct_gob)} gob-staging.hct_skeletons={len(hct_staging)}")

    fcp_content = _build_fcp_module(fcp_gob, fcp_staging)
    hct_content = _build_hct_module(hct_gob, hct_staging)

    FCP_FILE.write_text(fcp_content, encoding="utf-8")
    HCT_FILE.write_text(hct_content, encoding="utf-8")

    print(f"[sync] wrote {FCP_FILE}")
    print(f"[sync] wrote {HCT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

