#!/usr/bin/env python3
"""
Sync fallback FCP/HCT skeleton python files from one explicit MongoDB target.

Then rewrites:
- BackEnd/playcall_skeletons/fcp_skeletons.py
- BackEnd/playcall_skeletons/hct_skeletons.py

with source documents plus compatibility constants.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from pprint import pformat
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.db_migration_cli import connect_migration_target

FCP_FILE = ROOT / "BackEnd" / "playcall_skeletons" / "fcp_skeletons.py"
HCT_FILE = ROOT / "BackEnd" / "playcall_skeletons" / "hct_skeletons.py"


def _clean_docs(docs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    cleaned: list[dict[str, Any]] = []
    for doc in docs:
        d = dict(doc)
        d.pop("_id", None)
        cleaned.append(d)
    return cleaned


def _fetch_collection_docs(db, collection_name: str) -> list[dict[str, Any]]:
    coll = db[collection_name]
    docs = list(coll.find({}))
    return _clean_docs(docs)


def _extract_steps_for_variant(doc: dict[str, Any], variant_name: str, preferred_version: str = "v1") -> list[dict[str, Any]]:
    variants = doc.get("variants") or {}
    variant = variants.get(variant_name) or {}
    versions = variant.get("versions") or []
    if not isinstance(versions, list):
        return []

    chosen = None
    for version_doc in versions:
        if not isinstance(version_doc, dict):
            continue
        if version_doc.get("version") == preferred_version and version_doc.get("steps"):
            chosen = version_doc
            break

    if chosen is None:
        for version_doc in versions:
            if isinstance(version_doc, dict) and version_doc.get("steps"):
                chosen = version_doc
                break

    if chosen is None:
        return []
    steps = chosen.get("steps") or []
    return steps if isinstance(steps, list) else []


def _module_header(source_database: str) -> str:
    return (
        '"""\n'
        "Auto-generated fallback skeletons from MongoDB.\n\n"
        f"Source database: {source_database}\n\n"
        "Generated by: scripts/sync_fcp_hct_fallbacks_from_db.py\n"
        '"""\n\n'
    )


def _format_py(value: Any) -> str:
    # Keep output deterministic and readable.
    return pformat(value, width=110, sort_dicts=False)


def _build_fcp_module(
    docs: list[dict[str, Any]],
    source_database: str,
) -> str:
    primary = docs[0] if docs else {}
    base_steps = _extract_steps_for_variant(primary, "base", preferred_version="v1")

    # Keep legacy fallback behavior contract.
    fcp_1 = {
        "primary_shooter": None,
        "screener": None,
        "kickout_shooters": None,
        "steps": base_steps,
    }
    fcp_map = {
        "HCO": 1200,
        "Shot": 1800,
        "O_FOUL": 1200,
        "D_FOUL": 1200,
        "DEAD_BALL_TURNOVER": 900,
        "STEAL": 900,
    }

    return (
        _module_header(source_database)
        + f"SOURCE_DATABASE = {source_database!r}\n"
        + f"FCP_SKELETON_DOCS = {_format_py(docs)}\n\n"
        + "# ==================== compatibility fallback constants ====================\n"
        + f"FCP_1 = {_format_py(fcp_1)}\n\n"
        + f"FCP_SKELETONS_DICT = {_format_py(fcp_map)}\n"
    )


def _build_hct_module(
    docs: list[dict[str, Any]],
    source_database: str,
) -> str:
    primary = docs[0] if docs else {}
    base_steps = _extract_steps_for_variant(primary, "base", preferred_version="v1")

    hct_1 = {
        "primary_shooter": None,
        "screener": None,
        "kickout_shooters": None,
        "steps": base_steps,
    }
    hct_map = {
        "HCO": 1200,
        "SHOT": 1800,
        "O_FOUL": 1200,
        "D_FOUL": 900,
        "DEAD_BALL_TURNOVER": 900,
        "STEAL": 900,
    }
    hct_scenes = [hct_1]

    return (
        _module_header(source_database)
        + f"SOURCE_DATABASE = {source_database!r}\n"
        + f"HCT_SKELETON_DOCS = {_format_py(docs)}\n\n"
        + "# ==================== compatibility fallback constants ====================\n"
        + f"HCT_1 = {_format_py(hct_1)}\n\n"
        + f"HCT_SKELETONS_DICT = {_format_py(hct_map)}\n\n"
        + f"HCT_SCENES = {_format_py(hct_scenes)}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", required=True, choices=["gob-staging", "gob"])
    args = parser.parse_args()
    connection = connect_migration_target(args.db, write=False)
    db = connection.database

    fcp_docs = _fetch_collection_docs(db, "fcp_skeletons")
    hct_docs = _fetch_collection_docs(db, "hct_skeletons")
    connection.close()

    print(f"[sync] {args.db}.fcp_skeletons={len(fcp_docs)}")
    print(f"[sync] {args.db}.hct_skeletons={len(hct_docs)}")

    fcp_content = _build_fcp_module(fcp_docs, args.db)
    hct_content = _build_hct_module(hct_docs, args.db)

    FCP_FILE.write_text(fcp_content, encoding="utf-8")
    HCT_FILE.write_text(hct_content, encoding="utf-8")

    print(f"[sync] wrote {FCP_FILE}")
    print(f"[sync] wrote {HCT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
